### ISSUE TITLE
Problem Statement Documet

### ISSUE THREAD

**Issue by nathan20021** [RezaJodeiri/CXR-Capstone#8]
**Artifact Under Review**
`/docs/ProblemStatementAndGoals/ProblemStatement.tex`

**Description of Issue**

Section 1 @RezaJodeiri @Kd020819 
Section 2, 3 @AymanAkhras 
Section 4 @nathan20021 
Appendix @LongpanZhou 

Deadline 23/September/2024

**Comment by LongpanZhou** [comment]
Closed since work is due and done.
